name: ticmind
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter

  intro_slider: ^4.2.0
  flex_color_scheme: ^7.0.4
  uuid: ^3.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  calender_picker: ^2.0.1
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  google_sign_in: ^6.1.0
  table_calendar: ^3.0.8
  url_launcher: ^6.1.10
  share_plus: ^4.5.3
  firebase_analytics: ^10.3.0
  flutter_local_notifications: ^9.7.0
  timezone: ^0.8.0
 
  flutter_timezone: ^1.0.4
  flutter_easyloading: ^3.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


  assets:
    - assets/images/
